---
- name: Server Setup
  hosts: host
  remote_user: root


  vars:
    sqlpass: abcdef


  tasks:
    - name: set date and time
      shell: timedatectl set-timezone Africa/Lagos

    - name: set host name
      shell: hostnamectl set-hostname server.domainname.com

    - name: update cache
      shell: apt update -y && apt upgrade -y

    - name: Install pip
      shell: apt install python3-pip -y

    - name: use pip to install pymysql
      shell: python3 -m pip install PyMySQL

    - name: use pip to install cryptography
      shell: pip install cryptography

    - name: Install git
      shell: apt install git -y

    - name: Install software property and others
      apt:
        name:
          - lsb-release
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - gnupg2
          - curl
          - wget
          - debconf-utils
          - libaio1

    - name: Install apache2
      apt:
        name:
          - apache2
          - apache2-utils

    - name: Add apt repository
      apt_repository:
        repo: ppa:ondrej/php

    - name: update cache
      apt:
        update_cache: true
        upgrade: true

    - name: Install php
      apt:
        name: 
          - php8.1-fpm
          - libapache2-mod-php8.1
          - php8.1-cli
          - php8.1-common
          - php8.1-mysql
          - php8.1-opcache
          - php8.1-soap
          - php8.1-zip
          - php8.1-intl
          - php8.1-bcmath
          - php8.1-xml
          - php8.1-xmlrpc
          - php8.1-curl
          - php8.1-gd
          - php8.1-imagick
          - php8.1-cli
          - php8.1-dev
          - php8.1-imap
          - php8.1-mbstring

    - name: download composer
      shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

    - name: download composer
      shell: php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

    - name: composer setup
      shell: php composer-setup.php

    - name: unlink composer
      shell: php -r "unlink('composer-setup.php');"

    - name: move composer
      shell: mv composer.phar /usr/local/bin/composer

    - name: mysql
      shell:
        debconf-set-selections <<EOF
        mysql-apt-config mysql-apt-config/select-server select mysql-8.0
        "mysql-community-server mysql-community-server/root-pass password {{ sqlpass }}"
        "mysql-community-server mysql-community-server/re-root-pass password {{ sqlpass }}"
        EOF

    - name: mysql
      shell: wget --user-agent="Mozilla" -O /tmp/mysql-apt-config_0.8.24-1_all.deb https://dev.mysql.com/get/mysql-apt-config_0.8.24-1_all.deb


    - name: mysql
      shell: DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/mysql-apt-config_0.8.24-1_all.deb < /dev/null > /dev/null

    - name: update cache
      apt:
        update_cache: true
        upgrade: true

    - name: set database
      shell: DEBIAN_FRONTEND=noninteractive apt-get install mysql-server mysql-client --assume-yes --force-yes < /dev/null > /dev/null

    - name: database name
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - CREATE DATABASE laravelapp;

    - name: database user
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - CREATE USER 'laravelapp'@'localhost' IDENTIFIED BY 'laravelapp';

    - name: grant priviledges 
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - GRANT ALL PRIVILEGES ON laravelapp.* TO 'laravelapp'@'localhost';

    - name: flush priviledges
      command: 'mysql -ne "{{ item }}"'
      with_items:
        - FLUSH PRIVILEGES;

    - name: postgresql
      copy:
        src: /home/skylarng89/github/altschool-cloud-exercises/second_semester_exam/pgsql.sh
        dest: /root
        mode: '0775'

    - name: run bash script
      command: bash /root/pgsql.sh

    - name: clone from git
      git:
        repo: https://github.com/f1amy/laravel-realworld-example-app.git
        dest: /var/www/laravelapp

    - name: setup .emv
      copy:
        dest: /var/www/laravelapp/.env
        content: |
          APP_NAME="Laravel App"
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost
          APP_PORT=3000

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=debug

          DB_CONNECTION=mysql
          DB_HOST=localhost
          DB_PORT=3306
          DB_DATABASE=laravelapp
          DB_USERNAME=laravelapp
          DB_PASSWORD=laravelapp

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1

          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_MAILER=smtp
          MAIL_HOST=mailhog
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@example.com"
          MAIL_FROM_NAME="${APP_NAME}"

          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_APP_CLUSTER=mt1

          MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

          L5_SWAGGER_GENERATE_ALWAYS=true
          SAIL_XDEBUG_MODE=develop,debug
          SAIL_SKIP_CHECKS=true

    - name: setup route
      blockinfile:
        path: /var/www/laravelapp/routes/web.php
        marker: ""
        block: |
          Route::get('/', function () {
            return view('welcome');
          });

    - name: setup .htaccess
      copy:
        dest: "/var/www/laravelapp/.htaccess"
        content: |
          <IfModule mod_rewrite.c>
            RewriteEngine On

            RewriteCond %{REQUEST_URI} !^/public/
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f

            RewriteRule ^(.*)$ /public/$1
            RewriteRule ^(/)?$ public/index.php [L]
          </IfModule>

    - name: change ownership
      shell: chown -R root:root /var/www/laravelapp

    - name: change permission
      shell: chmod -R 0775 /var/www/laravelapp

    - name: change permission for storage
      shell: chown -R 0755 /var/www/laravelapp/storage

    - name: change for booststrap
      shell: chown -R 0755 /var/www/laravelapp/bootstrap/cache

    - name: composer create-project
      shell: cd /var/www/laravelapp && composer create-project -n

    - name: migrate seed
      shell:
        cmd: cd /var/www/laravelapp && php artisan migrate --seed

    - name: setup virtual host
      copy:
        dest: "/etc/apache2/sites-available/laravelapp.conf"
        content: |
          <VirtualHost *:80>
              ServerAdmin email@domain.com
              ServerName subdomain.domain.com
              ServerAlias subdomain.domain.com

              DocumentRoot /var/www/laravelapp/public

              <Directory /var/www/laravelapp/public>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: disable site
      shell: a2dissite 000-default.conf

    - name: enable laravel
      shell: a2ensite laravelapp.conf

    - name: mod rewrite
      shell: a2enmod rewrite

    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: change ownership
      shell: chown -R www-data:www-data /var/www/laravelapp

    - name: Insatll snap
      apt:
        name:
          - snapd

    - name: Use snap to inatall core
      shell: snap install core


    - name: refresh core
      shell: snap refresh core

    - name: Insatll certbot
      shell: snap install --classic certbot


    - name: Insert name
      shell: ln -s /snap/bin/certbot /usr/bin/certbot


    - name: Insert name
      shell:
        cmd: yes | certbot --apache --agree-tos --redirect -m email@domain.com -d subdomain.domain.com
